kubeProxyReplacement: strict
k8sServiceHost: "{{ ansible_host }}"
externalIPs:
    enabled: true
k8sServicePort: 6443
bpf:
  hostLegacyRouting: false
  masquerade: true
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  enabled: true
  listenAddress: ":4244"
  tls:
    enabled: true
    auto:
      enabled: true
      method: helm
      certValidityDuration: 1095
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 31235
  metrics:
    enableOpenMetrics: true
    enabled: "{dns:query;ignoreAAAA,drop,flow,flows-to-world,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction,icmp,port-distribution,tcp}"