- name: Check status of API server 
  shell: "kubectl get pods -n kube-system |grep api"
  ignore_errors: true
  register: api_status

- name: Initialize the Kubernetes cluster using kubeadm
  shell: "kubeadm init --control-plane-endpoint={{ ansible_host }}  --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr 10.1.1.0/24 --cri-socket=unix:///var/run/cri-dockerd.sock"
  register: kubeadm_init
  when: api_status.stdout_lines | length == 0

- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: 0644

## Install CILIUM plugin using HELM

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"
    
- name: Separately update the repository cache
  kubernetes.core.helm:
    name: cilium
    namespace: kube-system
    state: absent
    update_repo_cache: true

- name: Copy cilium-values.yaml to remote
  copy:
    src: cilium-values.yaml
    dest: /tmp/cilium-values.yaml
    remote_src: false

- name: Deploy Cilium chart using values files on target
  kubernetes.core.helm:
    name: cilium # Name of HELM Deployment
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values_files:
    - /tmp/cilium-values.yaml


  