- name: Check status of API server 
  shell: "kubectl get pods -n kube-system |grep api"
  ignore_errors: true
  register: api_status

- name: Initialize the Kubernetes cluster using kubeadm
  shell: "kubeadm init --control-plane-endpoint=192.168.1.22  --apiserver-advertise-address=192.168.1.22  --pod-network-cidr=10.244.0.0/16" ## --skip-phases=addon/kube-proxy"  ###--apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=192.168.159.0/16  --cri-socket=unix:///var/run/cri-dockerd.sock" ##10.244.0.0/16 10.1.1.0/24
  register: kubeadm_init
  when: api_status.stdout_lines | length == 0

- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: 0600