- name: Check status of API server 
  shell: "kubectl get pods -n kube-system |grep api"
  ignore_errors: true
  register: api_status

- name: Initialize the Kubernetes cluster using kubeadm
  shell: "kubeadm init --control-plane-endpoint={{ ansible_host }}  --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr 10.1.1.0/24 --cri-socket=unix:///var/run/cri-dockerd.sock"
  register: kubeadm_init
  when: api_status.stdout_lines | length == 0

- name: Create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: 0644

- name: Download Cilium Binary
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz"
    dest: "/tmp/cilium-linux-amd64.tar.gz"

- name: Unarchive bundle
  unarchive:
    src: "/tmp/cilium-linux-amd64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    #extra_opts:
    #- "--strip-components=1"

- name: Check status of Cilium Pod 
  shell: "kubectl get pods -n kube-system |grep cilium-operator |grep Running"
  ignore_errors: true
  register: cilium_status    

- name: Install Cilium
  shell: |
    cilium install
  when: cilium_status.stdout_lines | length == 0