- name: Add Kubernetes signing key
  apt_key:
    url:  https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ "
    state: present
    filename: 'kubernetes.list'


- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]

- name: Hold Kubernetes packages to prevent unintended upgrades
  apt:
    name: "{{ item }}"
    state: hold
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]
