- name: Add Kubernetes signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: 'kubernetes.list'

- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]

- name: Hold Kubernetes packages to prevent unintended upgrades
  apt:
    name: "{{ item }}"
    state: hold
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]
