
## install only packages
## kubelet default config -- cgroup
## docker config.yaml cgroup
- name: Ensure Docker group exists
  group:
    name: docker
    gid: 600
    state: present

- name: Ensure sysops user exists and is part of Docker Group
  user:
    name: sysops
    groups: docker
    append: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
  - docker.io
  #- docker-ce
  #- docker-ce-cli
  #- containerd.io
  #- docker-buildx-plugin
  #- docker-compose-plugin


- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started



