
- name: register status of /etc/apt/keyrings/kubernetes-apt-keyring.gpg file
  stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: keyring

- name: Add Kubernetes signing key
  shell: |
    curl -fsSL  https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: "not keyring.stat.exists"

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: 'kubernetes'
  when: "not keyring.stat.exists"


- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]

- name: Hold Kubernetes packages to prevent unintended upgrades
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]

- name: Add --node-ip in kubelet config
  lineinfile:
    path: /etc/sysconfig/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: KUBELET_EXTRA_ARGS="--node-ip"

-  name: Reload Systemd
   shell: systemctl daemon-reload

#-  name: Start Kubelet
 #  service:
  #   name: kubelet
   #  state: started 
