- name: Hold Kubernetes packages to prevent unintended upgrades
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]
  
- name: Add Kubernetes signing key
  shell: |
    curl -fsSL  https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: 'kubernetes'


- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]

- name: Hold Kubernetes packages to prevent unintended upgrades
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: [ 'kubelet', 'kubeadm', 'kubectl' ]
