- name: Fetch join command from master
  shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "master1"
  run_once: true

- name: Join node to the Kubernetes cluster
  shell: "{{ join_command.stdout }}" ## --cri-socket=unix:///var/run/cri-dockerd.sock"
  args:
    chdir: $HOME
    creates: /etc/kubernetes/kubelet.conf


- name: Enable kubelet 
  service:
    name: kubelet
    state: started
    enabled: true

- name: Add cron job to comment 'search' line in /etc/resolv.conf
  cron:
    name: "Comment 'search' line in /etc/resolv.conf"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "sed -i '/^search/s/^/# /' /etc/resolv.conf"
