- name: Fetch join command from master
  shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "master1"
  run_once: true

- name: Join node to the Kubernetes cluster
  shell: "{{ join_command.stdout }}"
  args:
    chdir: $HOME
    creates: /etc/kubernetes/kubelet.conf