- name: Install Python3
  package:
    name: python3
    state: present

- name: Install yum required packages
  package:
    name: "{{item}}"
    state: present
  loop:
  - python3-pip
  - tree

- name: Install yum required packages
  package:
    name: "{{item}}"
    state: hold
  loop:
  - python3-pip
  - tree
  - python3

- name: Install Pip3 packages
  pip:
    name: "{{item}}"
    executable: pip3
  loop:
  - hvac==1.1.1
  - kubernetes==26.1.0
  - openshift==0.13.1
