- name: Adding entry in /etc/hosts
  hosts: all  # This will run on all managed hosts

  become: true

  tasks:
  - name: Add Conf for containerd
    blockinfile:
      path: "/etc/hosts"
      block: |
        192.168.1.22 192.168.56.122 server2
        192.168.1.23 192.168.56.123 server3
        192.168.1.24 192.168.56.124 server4
        192.168.1.130 192.168.56.130 server10
        192.168.1.31 192.168.56.131 server11
        192.168.1.32 192.168.56.132 server12

  - name: Create Shared directory
    file:
      path: /shared1
      state: directory
      mode: '0755'

  - mount:
      path: /shared1
      src: shared1
      fstype: vboxsf
      state: present
      
 # - name: Configure NTP
  #  apt:
   #   name: ntpdate
    #  state: present

  #- name: configure ntp
   # yum:
    #  name: ntp
     # state: present
    #when: inventory_hostname not in 'server6'

  #- name: execute shell
   # shell: |
    #  "ntpdate ntp.ntsc.ac.cn"
     # "hwclock"
  
  #- name: Apt update
   # apt:
    #  upgrade: yes
     # update_cache: yes
      
