- name: installing and setup nfs
  hosts: all  

  become: true

  tasks:
  - name: Configure NFS server
    block:

    - name: NFS package
      apt:
        name: nfs-kernel-server
        state: present
      
    - name: NFS package
      apt:
        name: nfs-common
        state: present
   
    - name: Create NFS directory
      file:
        path: '/srv/nfs/share'
        state: directory
        mode: 0777
        owner: nobody
        group: nogroup
    
    - name: Add Conf for containerd
      blockinfile:
        path: "/etc/exports"
        block: |
          /srv/nfs/share 192.168.1.21(rw,sync,no_subtree_check)
          /srv/nfs/share 192.168.1.22(rw,sync,no_subtree_check)
          /srv/nfs/share 192.168.1.23(rw,sync,no_subtree_check)
          /srv/nfs/share 192.168.1.24(rw,sync,no_subtree_check)
          /srv/nfs/share 192.168.1.25(rw,sync,no_subtree_check)
          /srv/nfs/share 192.168.1.26(rw,sync,no_subtree_check)
    

    - name: Refresh exports
      shell: "exportfs -a"
    

    - name: Start nfs-kernel-server
      systemd_service:
        name: nfs-kernel-server
        state: started
        enabled: true
    when: inventory_hostname in 'server6'

  - name: Create directory to be mounted
    file:
      path: /nfs/volume1
      state: directory

  - name: Mount directories
    mount:
      src: 192.168.1.26:/srv/nfs/share
      path: /nfs/volume1
      state: mounted
      fstype: nfs
  
