- name: Create Kube-Prometheus deployment
  hosts: master1
  become: true

  tasks:
  
  - name: Create a k8s Monitoring namespace for chart deployment
    kubernetes.core.k8s:
      name: monitoring
      api_version: v1
      kind: Namespace
      state: present


  - name: Copy kube-prometheus-values.yaml to remote
    template:
      src: kube-prometheus-values.j2
      dest: /tmp/kube-prometheus.yaml

  
  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: prometheus-community
      repo_url: "https://prometheus-community.github.io/helm-charts"

    
  - name: Deploy Apisix chart using values files on target
    kubernetes.core.helm:
      name: prometheus-stack
      chart_ref: prometheus-community/kube-prometheus-stack
      release_namespace: monitoring
      values_files:
      - /tmp/kube-prometheus.yaml