- name: Adding entry in /etc/hosts
  hosts: all  # This will run on all managed hosts

  become: true

  tasks:
  - name: Add Conf for containerd
    blockinfile:
      path: "/etc/hosts"
      block: |
        192.168.1.22 server2
        192.168.1.23 server3
        192.168.1.24 server4

  - name: Create Shared directory
    file:
      path: /shared1
      type: directory

  - mount:
      path: /shared1
      src: shared1
      fstype: vboxsf
      state: present
      
  - name: Configure NTP
    apt:
      name: ntpdate
      state: present

  - name: execute shell
    shell: |
      "ntpdate ntp.ntsc.ac.cn"
      "hwclock"
  
  - name: Apt update
    apt:
      upgrade: yes
      update_cache: yes
      
