- name: Create APISIX deployment
  hosts: master1
  become: true

  tasks:
  
  - name: Create directory based on hostname pattern
    file:
      path: "/nfs/volume1/pv/{{item}}"
      state: directory
      mode: 0777
    loop:
    - apisix/etcd-volume-1
    - apisix/etcd-volume-2
    - apisix/etcd-volume-3

 
  - name: Create PVs
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', 'etcd-pv-nfs.yaml') }}"

  - name: Create a k8s Apisix namespace for chart deployment
    kubernetes.core.k8s:
      name: ingress-apisix
      api_version: v1
      kind: Namespace
      state: present


  - name: Copy apisix-values.yaml to remote
    template:
      src: apisix-values.j2
      dest: /tmp/apisix-values.yaml

  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: apisix
      repo_url: "https://charts.apiseven.com"

  
  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: "https://charts.bitnami.com/bitnami"

    
  - name: Deploy Apisix chart using values files on target
    kubernetes.core.helm:
      name: apisix # Name of HELM Deployment
      chart_ref: apisix/apisix
      release_namespace: ingress-apisix
      values_files:
      - /tmp/apisix-values.yaml
    #values:
      #kubeProxyReplacement: strict
 

  - name: Create a k8s Metallb namespace for chart deployment
    kubernetes.core.k8s:
      name: metallb-system
      api_version: v1
      kind: Namespace
      state: present
  

  - name: Add stable chart repo for Metallb
    kubernetes.core.helm_repository:
      name: metallb
      repo_url: "https://metallb.github.io/metallb"
   

  - name: Set Strictarp to True
    shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl apply -f - -n kube-system"

    
  - name: Deploy Metallb chart using values files on target
    kubernetes.core.helm:
      name: metallb # Name of HELM Deployment
      chart_ref: metallb/metallb
      release_namespace: metallb-system


  - name: Create Ip Address pool
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', 'ip-pool1.yaml') }}"


  - name: Announce at L2
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', 'announce-l21.yaml') }}"
 

  



  