- name: Create APISIX deployment
  hosts: all
  become: true

  tasks:
  
  - name: Create directory based on hostname pattern
    file:
      path: "/pv/{{item}}"
      state: directory
      mode: 0755
    when: inventory_hostname in 'worker1'
    loop:
    - etcd-volume-1
    - etcd-volume-2

  - name: Create directory based on hostname pattern
    file:
      path: "/pv/{{item}}"
      state: directory
      mode: 0755
    when: inventory_hostname in 'worker2'
    loop:
    - etcd-volume-3

  - name: Create PVs
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('file', 'etcd-pv.yaml') }}"
    when: inventory_hostname in 'master1'

  - name: Create a k8s Apisix namespace for chart deployment
    kubernetes.core.k8s:
      name: ingress-apisix
      api_version: v1
      kind: Namespace
      state: present
    when: inventory_hostname in 'master1'

  - name: Copy apisix-values.yaml to remote
    template:
      src: apisix-values.j2
      dest: /tmp/apisix-values.yaml
    when: inventory_hostname in 'master1'

  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: apisix
      repo_url: "https://charts.apiseven.com"
    when: inventory_hostname in 'master1'
  
  - name: Add stable chart repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: "https://charts.bitnami.com/bitnami"
    when: inventory_hostname in 'master1'
    
  - name: Deploy Apisix chart using values files on target
    kubernetes.core.helm:
      name: apisix # Name of HELM Deployment
      chart_ref: apisix/apisix
      release_namespace: ingress-apisix
      values_files:
      - /tmp/apisix-values.yaml
    #values:
      #kubeProxyReplacement: strict
    when: inventory_hostname in 'master1'  