---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume-1
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/etcd-volume-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume-2
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/etcd-volume-2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume-3
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/etcd-volume-3"