---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume-1
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server3
  volumeMode: Filesystem
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/etcd-volume-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume-2
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server3
  volumeMode: Filesystem
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/etcd-volume-2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-volume-3
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server4
  volumeMode: Filesystem
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/etcd-volume-3"